#!/usr/bin/env bash
# Generates the Dart client of the API (frontend/packages/library_api) from docs/api/openapi.yaml.
# The contract itself is regenerated by the backend: cd backend && ./gradlew integrationTest
# Requirements: Java (JAVA_HOME or java on PATH) and Flutter (dart on PATH).
set -euo pipefail

GENERATOR_VERSION="7.26.0"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CACHE="$ROOT/scripts/.cache"
JAR="$CACHE/openapi-generator-cli-$GENERATOR_VERSION.jar"
OUT="$ROOT/frontend/packages/library_api"
JAVA="${JAVA_HOME:+$JAVA_HOME/bin/}java"

if [ ! -f "$JAR" ]; then
  mkdir -p "$CACHE"
  curl -fsSL -o "$JAR" \
    "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/$GENERATOR_VERSION/openapi-generator-cli-$GENERATOR_VERSION.jar"
fi

# Empty the folder rather than delete it: Windows keeps a watched folder locked.
mkdir -p "$OUT"
find "$OUT" -mindepth 1 -delete
"$JAVA" -jar "$JAR" generate \
  --input-spec "$ROOT/docs/api/openapi.yaml" \
  --generator-name dart-dio \
  --output "$OUT" \
  --additional-properties=pubName=library_api,pubLibrary=library_api,pubDescription="Client Dart généré pour Library",serializationLibrary=json_serializable \
  --global-property=apiTests=false,modelTests=false,apiDocs=false,modelDocs=false

# json_serializable now emits null-aware map elements (Dart 3.8) and the template has no homepage.
sed -i -e "s/^  sdk: .*/  sdk: '^3.8.0'/" -e "/^homepage:/d" "$OUT/pubspec.yaml"

cd "$OUT"
dart pub get
dart run build_runner build --delete-conflicting-outputs
echo "Client generated in $OUT"
